name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: npm ci
      - run: npm run build
      - run: npm install gh-pages --save-dev
      - run: npm run deploy

      - name: Force gh-pages update
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout gh-pages
          git pull origin gh-pages
          git add .
          git commit -m "Auto-deploy from GitHub Actions"
          git push